### ISSUE TITLE
Goerli network?

### ISSUE THREAD

**Issue by ygengygeng** [Open-Attestation/open-attestation-cli#236]
Hi 
I am currently following the guide for https://www.openattestation.com/docs/integrator-section/verifiable-document/did/create and managed to generate and view the opencert file on both dev.opencerts.io and opencerts.io

I noticed that when I created the wallet with public address, the transaction details can be found on goerli.etherscan.io
Assuming the Goerli network goes down at a future date (similar to what happen to Ropsten), what happens to those certs that are issued with this document store created in Goerli network? Will they still be visible on opencerts.io?

Thanks.

**Comment by ygengygeng** [comment]
Add on question:
Following the steps in https://www.openattestation.com/docs/integrator-section/verifiable-document/ethereum/wallet, 
Is it possible to create a wallet using the cli in mainnet environment instead of goerli environment?

**Comment by HJunyuan** [comment]
Hi @ygengygeng, after a network is deprecated, certificates that have already been issued still remain in the document store.

Whether or not it is verifiable depends on the provider you use. For example, [Etherscan (Ropsten)](https://ropsten.etherscan.io) is still accessible in read-only mode. However, providers like Infura or Alchemy have chosen to [deprecate Ropsten access via their APIs](https://blog.infura.io/post/deprecation-timeline-for-rinkeby-ropsten-and-kovan-testnets). Since opencerts.io uses the Infura provider, Ropsten-issued certificates are no longer verifiable.
